### ISSUE TITLE
Illegal character '&' in raw string

### ISSUE THREAD

**Issue by dandunckelman** [puppetlabs/puppetlabs-powershell#158]
# Summary
When running an exec to install Wordpress with [webpicmd](https://www.iis.net/learn/install/web-platform-installer/web-platform-installer-v4-command-line-webpicmdexe-rtw-release), I get this error (formatted for readability):

```
#<RuntimeError: Illegal character '&' in raw string "

The software that you obtain using the Web Platform Installer Command Line Tool is licensed to you by its owner.
Microsoft grants you no rights for third party software. . .. ... . .. ...
Successfully loaded primary feed: https://go.microsoft.com/?linkid=9842185

Please choose a database for 'WordPress'
Selected database: 'MySQL'

Product 'Update for IIS 7.0 FastCGI' has no installers available for this platform
Product 'Update for IIS 7.0 FastCGI (KB980363)' has no installers available for this platform
Product 'Microsoft Visual C++ 2012 Redistributable Package' has no installers available for this platform

The following software is going to be installed:

EULA: 'IIS: WAS Process Model', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: WAS Configuration API', which is owned by 'Microsoft' will be turned on
EULA: '.NET 4.5 Extended with ASP.NET for Windows 8', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Static Content', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Default Document', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Directory Browsing', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: HTTP Errors', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: HTTP Logging', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Logging Tools', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Request Monitor', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Request Filtering', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Static Content Compression', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Management Console', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: CGI', which is owned by 'Microsoft' will be turned on
EULA: 'RunPHP Helper', which is owned by 'Unknown', will be downloaded from 'https://sourceforge.net/projects/phpinstallermsi/files/zip/runphp.zip/download'.
The license agreement to 'RunPHP Helper' may be included with the software.
You are responsible for and must separately locate, read and accept these license terms.
EULA: 'Web Deploy 3.5 - 2013', which is owned by 'Microsoft', will be downloaded from 'http://go.microsoft.com/fwlink/?LinkID=309497&clcid=0x409'. The license agreement to 'Web Deploy 3.5 - 2013' is available at 'http://go.microsoft.com/fwlink/?LinkId=309505&clcid=0x409'.
EULA: 'Web Deploy 3.5 without bundled SQL support', which is owned by 'Microsoft' will be installed The license agreement to 'Web Deploy 3.5 without bundled SQL support' may be included with the software. You are responsible for and must separately locate, read and accept these license terms.
EULA: 'Web Deploy 3.5 without bundled SQL support (latest)', which is owned by 'Microsoft' will be installed The license agreement to 'Web Deploy 3.5 without bundled SQL support (latest)' may be included with the software. You are responsible for and must separately locate, read and accept these license terms.
EULA: 'URL Rewrite 2.0', which is owned by 'Microsoft', will be downloaded from 'http://download.microsoft.com/download/C/9/E/C9E8180D-4E51-40A6-A9BF-776990D8BCA9/rewrite_amd64.msi'. The license agreement to 'URL Rewrite 2.0' is available at 'http://download.microsoft.com/download/6/9/C/69C1195A-123E-4BE8-8EDF-371CDCA4EC6C/License_rtw.htm'.
EULA: 'MySQL Connector/Net', which is owned by 'http://mysql.llarian.net/', will be downloaded from 'http://dev.mysql.com/get/Downloads/Connector-Net/mysql-connector-net-6.9.7.msi'. The license agreement to 'MySQL Connector/Net' may be included with the software. You are responsible for and must separately locate, read and accept these license terms.
EULA: 'PHP 5.5.38', which is owned by 'PHP.net', will be downloaded from 'http://sourceforge.net/projects/phpinstallermsi/files/zip/php-5.5.38-nts-Win32-VC11-x86.zip/download'. The license agreement to 'PHP 5.5.38' is available at 'http://www.php.net/license/3_01.txt'.
EULA: 'Windows Cache Extension 1.3 for PHP 5.5', which is owned by 'Microsoft', will be downloaded from 'http://sourceforge.net/projects/wincache/files/wincache-1.3.7/wincachewpi-1.3.7.11-5.5-nts-vc11-x86.exe/download'. The license agreement to 'Windows Cache Extension 1.3 for PHP 5.5' is available at 'http://svn.php.net/viewvc/pecl/wincache/trunk/LICENSE?view=markup'.
EULA: 'WordPress', which is owned by 'WordPress', will be downloaded from 'https://github.com/Atomthin/WordPress_Windows_package/blob/master/wordpress-4.6.1-IIS.zip?raw=true'. The license agreement to 'WordPress' may be included with the software. You are responsible for and must separately locate, read and accept these license terms.
EULA: 'MySQL Windows 5.1', which is owned by 'Unknown', will be downloaded from 'http://dev.mysql.com/get/Downloads/MySQL-5.1/mysql-5.1.73-winx64.msi'. The license agreement to 'MySQL Windows 5.1' may be included with the software. You are responsible for and must separately locate, read and accept these license terms.

Accepted EULA.
Starting Installation
Started downloading products..." >

c:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/text.rb:155:in `block in check'
c:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/text.rb:153:in `scan'
c:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/text.rb:153:in `check'
c:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/text.rb:120:in `initialize'
c:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/parsers/treeparser.rb:46:in `new'
c:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/parsers/treeparser.rb:46:in `parse'
c:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/document.rb:287:in `build'
c:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/document.rb:44:in `initialize'
C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/puppetlabs/powershell/powershell_manager.rb:82:in `new'
C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/puppetlabs/powershell/powershell_manager.rb:82:in `execute'
C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/provider/exec/powershell.rb:77:in `run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/type/exec.rb:130:in `block in sync'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/type/exec.rb:127:in `times'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/type/exec.rb:127:in `sync'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction/resource_harness.rb:189:in `sync'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction/resource_harness.rb:114:in `sync_if_needed'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction/resource_harness.rb:87:in `block in perform_changes'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction/resource_harness.rb:86:in `each'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction/resource_harness.rb:86:in `perform_changes'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction/resource_harness.rb:20:in `evaluate'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction.rb:212:in `apply'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction.rb:228:in `eval_resource'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction.rb:151:in `call'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction.rb:151:in `block (2 levels) in evaluate'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:386:in `block in thinmark'
c:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:385:in `thinmark'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction.rb:151:in `block in evaluate'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/graph/relationship_graph.rb:118:in `traverse'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction.rb:142:in `evaluate'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/resource/catalog.rb:222:in `block in apply'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util/log.rb:155:in `with_destination'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/transaction/report.rb:118:in `as_logging_destination'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/resource/catalog.rb:221:in `apply'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/configurer.rb:171:in `block in apply_catalog'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:223:in `block in benchmark'
c:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:222:in `benchmark'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/configurer.rb:170:in `apply_catalog'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/configurer.rb:315:in `run_internal'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/configurer.rb:186:in `block in run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/context.rb:65:in `override'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet.rb:240:in `override'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/configurer.rb:185:in `run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:45:in `block (4 levels) in run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/agent/locker.rb:21:in `lock'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:45:in `block (3 levels) in run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:98:in `with_client'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:42:in `block (2 levels) in run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:65:in `run_in_fork'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:41:in `block in run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:179:in `call'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:179:in `controlled_run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:39:in `run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application/agent.rb:353:in `onetime'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application/agent.rb:331:in `run_command'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:344:in `block in run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:540:in `exit_on_fail'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:344:in `run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util/command_line.rb:128:in `run'
c:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util/command_line.rb:72:in `execute'
c:/Program Files/Puppet Labs/Puppet/puppet/bin/puppet:5:in `<main>'

... Illegal character '&' in raw string "

The software that you obtain using the Web Platform Installer Command Line Tool is licensed to you by its owner.
Microsoft grants you no rights for third party software. . .. ... . .. ...
Successfully loaded primary feed: https://go.microsoft.com/?linkid=9842185

Please choose a database for 'WordPress'
Selected database: 'MySQL'
Product 'Update for IIS 7.0 FastCGI' has no installers available for this platform
Product 'Update for IIS 7.0 FastCGI (KB980363)' has no installers available for this platform
Product 'Microsoft Visual C++ 2012 Redistributable Package' has no installers available for this platform

The following software is going to be installed:

EULA: 'IIS: WAS Process Model', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: WAS Configuration API', which is owned by 'Microsoft' will be turned on
EULA: '.NET 4.5 Extended with ASP.NET for Windows 8', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Static Content', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Default Document', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Directory Browsing', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: HTTP Errors', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: HTTP Logging', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Logging Tools', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Request Monitor', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Request Filtering', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Static Content Compression', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: Management Console', which is owned by 'Microsoft' will be turned on
EULA: 'IIS: CGI', which is owned by 'Microsoft' will be turned on

EULA: 'RunPHP Helper', which is owned by 'Unknown', will be downloaded from 'https://sourceforge.net/projects/phpinstallermsi/files/zip/runphp.zip/download'.
The license agreement to 'RunPHP Helper' may be included with the software.
You are responsible for and must separately locate, read and accept these license terms.

EULA: 'Web Deploy 3.5 - 2013', which is owned by 'Microsoft', will be downloaded from 'http://go.microsoft.com/fwlink/?LinkID=309497&clcid=0x409'.
The license agreement to 'Web Deploy 3.5 - 2013' is available at 'http://go.microsoft.com/fwlink/?LinkId=309505&clcid=0x409'.

EULA: 'Web Deploy 3.5 without bundled SQL support', which is owned by 'Microsoft' will be installed
The license agreement to 'Web Deploy 3.5 without bundled SQL support' may be included with the software.
You are responsible for and must separately locate, read and accept these license terms.

EULA: 'Web Deploy 3.5 without bundled SQL support (latest)', which is owned by 'Microsoft' will be installed
The license agreement to 'Web Deploy 3.5 without bundled SQL support (latest)' may be included with the software. You are responsible for and must separately locate, read and accept these license terms.

EULA: 'URL Rewrite 2.0', which is owned by 'Microsoft', will be downloaded from 'http://download.microsoft.com/download/C/9/E/C9E8180D-4E51-40A6-A9BF-776990D8BCA9/rewrite_amd64.msi'.
The license agreement to 'URL Rewrite 2.0' is available at 'http://download.microsoft.com/download/6/9/C/69C1195A-123E-4BE8-8EDF-371CDCA4EC6C/License_rtw.htm'.

EULA: 'MySQL Connector/Net', which is owned by 'http://mysql.llarian.net/', will be downloaded from 'http://dev.mysql.com/get/Downloads/Connector-Net/mysql-connector-net-6.9.7.msi'.
The license agreement to 'MySQL Connector/Net' may be included with the software.
You are responsible for and must separately locate, read and accept these license terms.

EULA: 'PHP 5.5.38', which is owned by 'PHP.net', will be downloaded from 'http://sourceforge.net/projects/phpinstallermsi/files/zip/php-5.5.38-nts-Win32-VC11-x86.zip/download'.
The license agreement to 'PHP 5.5.38' is available at 'http://www.php.net/license/3_01.txt'.

EULA: 'Windows Cache Extension 1.3 for PHP 5.5', which is owned by 'Microsoft', will be downloaded from 'http://sourceforge.net/projects/wincache/files/wincache-1.3.7/wincachewpi-1.3.7.11-5.5-nts-vc11-x86.exe/download'.
The license agreement to 'Windows Cache Extension 1.3 for PHP 5.5' is available at 'http://svn.php.net/viewvc/pecl/wincache/trunk/LICENSE?view=markup'.

EULA: 'WordPress', which is owned by 'WordPress', will be downloaded from 'https://github.com/Atomthin/WordPress_Windows_package/blob/master/wordpress-4.6.1-IIS.zip?raw=true'.
The license agreement to 'WordPress' may be included with the software.
You are responsible for and must separately locate, read and accept these license terms.

EULA: 'MySQL Windows 5.1', which is owned by 'Unknown', will be downloaded from 'http://dev.mysql.com/get/Downloads/MySQL-5.1/mysql-5.1.73-winx64.msi'.
The license agreement to 'MySQL Windows 5.1' may be included with the software.
You are responsible for and must separately locate, read and accept these license terms.

Accepted EULA.
Starting Installation
Started downloading products..." Line: 1 Position: 5389 Last 80 unconsumed characters: <ReturnResult>
```

Here's my manifest:

```
class profile::wordpress::app::windows {
  $findstr  = 'c:/Windows/system32/findstr.exe'
  $webpicmd = 'c:/ProgramData/chocolatey/bin/WebpiCmd.exe'

  file { 'c:/tmp/wordpress.app':
    content => template('profile/wordpress.app.erb'),
    ensure  => file,
  }

  package { ['webpicmd', 'vcredist2012']:
    ensure   => present,
    provider => chocolatey,
  }->

  exec { 'Install Wordpress':
    command  => "$webpicmd /Install /Application:Wordpress@wordpress.app /MySQLPassword:dummypass /AcceptEula",
    cwd      => 'c:/tmp',
    provider => powershell,
    require  => File['c:/tmp/wordpress.app'],
    timeout  => 600,
    unless   => "$webpicmd /List /ListOption:Installed | $findstr Wordpress; if ($?) { exit 0 }",
  }
}
```

# Questions/Notes
- Should I be able to simply use `CMD > LOGFILE` to get it to avoid this?
- I could be wrong, but I couldn't find a **quiet** mode w/ `webpicmd`
- Environment Info
  - Running in PE 2016.2
  - Windows 2012R2

Please let me know if any further info is desired.

**Comment by ferventcoder** [comment]
@dandunckelman in this case, you may prefer to just use exec instead of powershell provider. 

Something like command `command => "cmd /c $webpicmd /Install /Application:Wordpress@wordpress.app /MySQLPassword:dummypass /AcceptEula"`

**Comment by dandunckelman** [comment]
Hey @ferventcoder.

Thanks for the idea!

My coworker recommend using ` | Out-Null`, which solved it (at least until the next problem :stuck_out_tongue_closed_eyes:)

I just might try your suggestion.  I'll close this as it's not really an issue necessitating work in this module.

Thanks again
